# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: protobuf/monitoring.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'protobuf/monitoring.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19protobuf/monitoring.proto\x12\nmonitoring\"\xc1\x01\n\rSystemMetrics\x12\x13\n\x0b\x63pu_percent\x18\x01 \x01(\x01\x12\x16\n\x0ememory_percent\x18\x02 \x01(\x01\x12\x16\n\x0ememory_used_mb\x18\x03 \x01(\x01\x12\x17\n\x0fmemory_total_mb\x18\x04 \x01(\x01\x12\x14\n\x0c\x64isk_read_mb\x18\x05 \x01(\x01\x12\x15\n\rdisk_write_mb\x18\x06 \x01(\x01\x12\x11\n\tnet_in_mb\x18\x07 \x01(\x01\x12\x12\n\nnet_out_mb\x18\x08 \x01(\x01\"\xce\x01\n\x0eMetricsRequest\x12\x10\n\x08hostname\x18\x01 \x01(\t\x12*\n\x07metrics\x18\x02 \x01(\x0b\x32\x19.monitoring.SystemMetrics\x12\x11\n\ttimestamp\x18\x03 \x01(\x03\x12:\n\x08metadata\x18\x04 \x03(\x0b\x32(.monitoring.MetricsRequest.MetadataEntry\x1a/\n\rMetadataEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"\x18\n\x07\x43ommand\x12\r\n\x05\x61gent\x18\x01 \x01(\t*&\n\x0b\x43ommandType\x12\n\n\x06\x43ONFIG\x10\x00\x12\x0b\n\x07\x43ONTROL\x10\x01\x32R\n\nMonitoring\x12\x44\n\rStreamMetrics\x12\x1a.monitoring.MetricsRequest\x1a\x13.monitoring.Command(\x01\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protobuf.monitoring_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_METRICSREQUEST_METADATAENTRY']._loaded_options = None
  _globals['_METRICSREQUEST_METADATAENTRY']._serialized_options = b'8\001'
  _globals['_COMMANDTYPE']._serialized_start=472
  _globals['_COMMANDTYPE']._serialized_end=510
  _globals['_SYSTEMMETRICS']._serialized_start=42
  _globals['_SYSTEMMETRICS']._serialized_end=235
  _globals['_METRICSREQUEST']._serialized_start=238
  _globals['_METRICSREQUEST']._serialized_end=444
  _globals['_METRICSREQUEST_METADATAENTRY']._serialized_start=397
  _globals['_METRICSREQUEST_METADATAENTRY']._serialized_end=444
  _globals['_COMMAND']._serialized_start=446
  _globals['_COMMAND']._serialized_end=470
  _globals['_MONITORING']._serialized_start=512
  _globals['_MONITORING']._serialized_end=594
# @@protoc_insertion_point(module_scope)
