# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: protobuf/monitoring.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'protobuf/monitoring.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import struct_pb2 as google_dot_protobuf_dot_struct__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19protobuf/monitoring.proto\x12\nmonitoring\x1a\x1cgoogle/protobuf/struct.proto\"\xc1\x01\n\rSystemMetrics\x12\x13\n\x0b\x63pu_percent\x18\x01 \x01(\x01\x12\x16\n\x0ememory_percent\x18\x02 \x01(\x01\x12\x16\n\x0ememory_used_mb\x18\x03 \x01(\x01\x12\x17\n\x0fmemory_total_mb\x18\x04 \x01(\x01\x12\x14\n\x0c\x64isk_read_mb\x18\x05 \x01(\x01\x12\x15\n\rdisk_write_mb\x18\x06 \x01(\x01\x12\x11\n\tnet_in_mb\x18\x07 \x01(\x01\x12\x12\n\nnet_out_mb\x18\x08 \x01(\x01\"\x8c\x01\n\x0eMetricsRequest\x12\x10\n\x08hostname\x18\x01 \x01(\t\x12*\n\x07metrics\x18\x02 \x01(\x0b\x32\x19.monitoring.SystemMetrics\x12\x11\n\ttimestamp\x18\x03 \x01(\x03\x12)\n\x08metadata\x18\x04 \x01(\x0b\x32\x17.google.protobuf.Struct\"Y\n\x07\x43ommand\x12%\n\x04type\x18\x01 \x01(\x0e\x32\x17.monitoring.CommandType\x12\'\n\x06params\x18\x02 \x01(\x0b\x32\x17.google.protobuf.Struct*2\n\x0b\x43ommandType\x12\x07\n\x03\x41\x43K\x10\x00\x12\n\n\x06\x43ONFIG\x10\x01\x12\x0e\n\nDIAGNOSTIC\x10\x02\x32R\n\nMonitoring\x12\x44\n\rStreamMetrics\x12\x1a.monitoring.MetricsRequest\x1a\x13.monitoring.Command(\x01\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protobuf.monitoring_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_COMMANDTYPE']._serialized_start=501
  _globals['_COMMANDTYPE']._serialized_end=551
  _globals['_SYSTEMMETRICS']._serialized_start=72
  _globals['_SYSTEMMETRICS']._serialized_end=265
  _globals['_METRICSREQUEST']._serialized_start=268
  _globals['_METRICSREQUEST']._serialized_end=408
  _globals['_COMMAND']._serialized_start=410
  _globals['_COMMAND']._serialized_end=499
  _globals['_MONITORING']._serialized_start=553
  _globals['_MONITORING']._serialized_end=635
# @@protoc_insertion_point(module_scope)
