# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import monitoring_pb2 as monitoring__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in monitoring_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class MonitoringServiceStub(object):
    """Service definition for Monitor Agent <-> gRPC Server communication
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StreamCommunication = channel.stream_stream(
                '/monitoring.MonitoringService/StreamCommunication',
                request_serializer=monitoring__pb2.AgentMessage.SerializeToString,
                response_deserializer=monitoring__pb2.ServerMessage.FromString,
                _registered_method=True)
        self.RegisterAgent = channel.unary_unary(
                '/monitoring.MonitoringService/RegisterAgent',
                request_serializer=monitoring__pb2.AgentRegistration.SerializeToString,
                response_deserializer=monitoring__pb2.Ack.FromString,
                _registered_method=True)


class MonitoringServiceServicer(object):
    """Service definition for Monitor Agent <-> gRPC Server communication
    """

    def StreamCommunication(self, request_iterator, context):
        """Bidirectional streaming for agent-server communication
        Agent streams: MetricsRequest, CommandResponseMessage
        Server streams: CommandMessage, Ack
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RegisterAgent(self, request, context):
        """Agent registers itself with the server (called once at startup)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MonitoringServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StreamCommunication': grpc.stream_stream_rpc_method_handler(
                    servicer.StreamCommunication,
                    request_deserializer=monitoring__pb2.AgentMessage.FromString,
                    response_serializer=monitoring__pb2.ServerMessage.SerializeToString,
            ),
            'RegisterAgent': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterAgent,
                    request_deserializer=monitoring__pb2.AgentRegistration.FromString,
                    response_serializer=monitoring__pb2.Ack.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'monitoring.MonitoringService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('monitoring.MonitoringService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class MonitoringService(object):
    """Service definition for Monitor Agent <-> gRPC Server communication
    """

    @staticmethod
    def StreamCommunication(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/monitoring.MonitoringService/StreamCommunication',
            monitoring__pb2.AgentMessage.SerializeToString,
            monitoring__pb2.ServerMessage.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RegisterAgent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/monitoring.MonitoringService/RegisterAgent',
            monitoring__pb2.AgentRegistration.SerializeToString,
            monitoring__pb2.Ack.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
